import 'dart:typed_data';
import 'package:http/http.dart' as http;

class PlantUmlService {
  static const String _krokiUrl = 'https://kroki.io/plantuml/png';

  static Future<Uint8List?> fetchUmlImage(String text) async {
    try {
      // Ensure text is wrapped in @startuml and @enduml
      if (!text.trim().startsWith('@startuml')) {
        text = '@startuml\n$text\n@enduml';
      }

      // Strip out any deprecated handwritten skinparams generated by the LLM
      text = text.replaceAll(RegExp(r'skinparam\s+handwritten\s+(true|false)'), '');

      // Inject transparent background and modern sleek styling
      text = text.replaceFirst(
        '@startuml',
        '''@startuml
skinparam backgroundcolor transparent
skinparam shadowing false
skinparam defaultFontName Inter, sans-serif
skinparam defaultFontSize 14
skinparam RoundCorner 16
skinparam ArrowColor #7b61ff
skinparam ArrowThickness 2
skinparam NodeBackgroundColor #FFFFFF
skinparam NodeBorderColor #7b61ff
skinparam NodeBorderThickness 2
skinparam UseCaseBackgroundColor #FFFFFF
skinparam UseCaseBorderColor #7b61ff
skinparam UseCaseBorderThickness 2
skinparam RectangleBackgroundColor #FFFFFF
skinparam RectangleBorderColor #7b61ff
skinparam RectangleBorderThickness 2
<style>
mindmapDiagram {
    node {
        BackgroundColor #FFFFFF
        BorderColor #7b61ff
        BorderThickness 2
        RoundCorner 16
        FontColor #333333
        Padding 12
    }
    arrow {
        LineThickness 2
        LineColor #7b61ff
    }
}
</style>''',
      );

      final response = await http.post(
        Uri.parse(_krokiUrl),
        body: text,
        headers: {'Content-Type': 'text/plain'},
      );

      if (response.statusCode == 200) {
        return response.bodyBytes;
      } else {
        print('Kroki returned error: \${response.statusCode}');
      }
    } catch (e) {
      print('Error fetching UML image: $e');
    }
    return null;
  }
}
