import 'dart:ui' as ui;
import 'package:flutter/material.dart';
import '../models/stroke.dart';
import '../models/tool_type.dart';
import 'dart:convert';
import 'package:google_fonts/google_fonts.dart';
import 'logic/components/component_registry.dart';
import 'logic/models/circuit_pin.dart';

class BackgroundPainter extends CustomPainter {
  @override
  void paint(Canvas canvas, Size size) {
    // Draw white background
    final bgPaint = Paint()..color = Colors.white;
    canvas.drawRect(Rect.fromLTWH(0, 0, size.width, size.height), bgPaint);
  }

  @override
  bool shouldRepaint(covariant CustomPainter oldDelegate) => false;
}

class DrawingCanvasPainter extends CustomPainter {
  final List<Stroke> strokes;
  // Instance-level cache — NOT static, so each page gets its own cache
  ui.Picture? _cachedPicture;
  int _cachedStrokeCount = -1;

  DrawingCanvasPainter({required this.strokes});

  @override
  void paint(Canvas canvas, Size size) {
    // Wrap everything in a saveLayer so BlendMode.clear only clears strokes and not the background
    canvas.saveLayer(Rect.fromLTWH(0, 0, size.width, size.height), Paint());

    // Cache static strokes (all but the last active stroke)
    final staticCount = strokes.isNotEmpty ? strokes.length - 1 : 0;

    if (_cachedStrokeCount != staticCount) {
      final recorder = ui.PictureRecorder();
      final cacheCanvas = Canvas(recorder);

      for (int i = 0; i < staticCount; i++) {
        _drawStroke(cacheCanvas, strokes[i]);
      }

      _cachedPicture = recorder.endRecording();
      _cachedStrokeCount = staticCount;
    }

    if (_cachedPicture != null) {
      canvas.drawPicture(_cachedPicture!);
    }

    // Always draw the active (last) stroke
    if (strokes.isNotEmpty) {
      _drawStroke(canvas, strokes.last);
    }

    canvas.restore();
  }

  void _drawStroke(Canvas canvas, Stroke stroke) {
    if (stroke.points.isEmpty) return;

    // Chemistry strokes are rendered by ChemistryWidget in canvas_widget.dart
    if (stroke.smiles != null) return;

    final isHighlighter = stroke.toolType == ToolType.highlighter;
    final isEraser = stroke.toolType == ToolType.eraser;
    final isBrush = stroke.toolType == ToolType.brush;
    final isFill = stroke.toolType == ToolType.fill;

    final paint = Paint()
      ..color = isHighlighter
          ? stroke.color.withOpacity(0.4)
          : (isEraser ? Colors.white : stroke.color)
      ..strokeWidth = isHighlighter ? stroke.size * 2 : stroke.size
      ..strokeCap = isHighlighter ? StrokeCap.square : StrokeCap.round
      ..strokeJoin = StrokeJoin.round
      ..style = (stroke.isFilled || isFill)
          ? PaintingStyle.fill
          : PaintingStyle.stroke;

      if (isBrush) {
        paint.maskFilter = MaskFilter.blur(BlurStyle.normal, stroke.size / 2);
      }

      if (isHighlighter) {
        paint.blendMode = BlendMode.multiply;
      } else if (isEraser) {
        paint.blendMode = BlendMode.clear;
      }

      if (stroke.decodedImage != null) {
        final imagePaint = Paint()..filterQuality = FilterQuality.high;
        
        if (stroke.text == 'chemistry') {
          // Removes the solid white/gray background generated by PubChem API
          imagePaint.blendMode = BlendMode.multiply;
          // Increase brightness/contrast slightly so the gray (#F5F5F5) becomes pure white (#FFFFFF).
          // Pure white combined with BlendMode.multiply makes the background completely transparent!
          imagePaint.colorFilter = const ColorFilter.matrix([
            1.1, 0, 0, 0, 0,
            0, 1.1, 0, 0, 0,
            0, 0, 1.1, 0, 0,
            0, 0, 0, 1.0, 0,
          ]);
        }

        canvas.save();
        canvas.translate(stroke.points.first.dx, stroke.points.first.dy);
        if (stroke.rotation != 0.0) {
          canvas.rotate(stroke.rotation);
        }
        if (stroke.size != 1.0) {
          canvas.scale(stroke.size, stroke.size);
        }
        
        if (stroke.animationProgress != null && stroke.animationProgress! < 1.0) {
          final progress = stroke.animationProgress!;
          final width = stroke.decodedImage!.width.toDouble();
          final height = stroke.decodedImage!.height.toDouble();
          canvas.clipRect(Rect.fromLTWH(0, 0, width * progress, height));
        }

        canvas.drawImage(stroke.decodedImage!, Offset.zero, imagePaint);
        canvas.restore();
        return;
      }

      if (stroke.toolType == ToolType.latex) {
        // LaTeX is rendered independently via Math.tex in canvas_widget.dart,
        // so we don't paint it here on the raw canvas.
        return;
      }

      if (stroke.toolType == ToolType.widget && stroke.text != null) {
        try {
          final data = jsonDecode(stroke.text!);
          if (data['action'] == 'insert_widget' && data['type'] == 'weather') {
            final loc = data['location'] ?? 'Unknown';
            final temp = data['temp'] ?? '--';
            final cond = data['condition'] ?? 'Clear';
            final p = stroke.points.isNotEmpty ? stroke.points.first : Offset.zero;

            final cardRect = Rect.fromLTWH(p.dx, p.dy, 250, 120);
            final cardPaint = Paint()
              ..color = Colors.blueGrey.shade800
              ..style = PaintingStyle.fill
              ..maskFilter = const MaskFilter.blur(BlurStyle.solid, 4);

            canvas.drawRRect(RRect.fromRectAndRadius(cardRect, const Radius.circular(16)), cardPaint);

            final tpLoc = TextPainter(
              text: TextSpan(text: "$loc", style: const TextStyle(color: Colors.white, fontSize: 24, fontWeight: FontWeight.bold)),
              textDirection: TextDirection.ltr,
            )..layout();
            tpLoc.paint(canvas, Offset(p.dx + 20, p.dy + 20));

            final tpTemp = TextPainter(
              text: TextSpan(text: "$temp", style: const TextStyle(color: Colors.cyanAccent, fontSize: 36, fontWeight: FontWeight.bold)),
              textDirection: TextDirection.ltr,
            )..layout();
            tpTemp.paint(canvas, Offset(p.dx + 20, p.dy + 55));

            final tpCond = TextPainter(
              text: TextSpan(text: "$cond", style: const TextStyle(color: Colors.white70, fontSize: 20)),
              textDirection: TextDirection.ltr,
            )..layout();
            tpCond.paint(canvas, Offset(p.dx + 120, p.dy + 65));
            return;
          }
        } catch (_) {}
      }

      if (stroke.text != null &&
          !stroke.text!.startsWith('{"type":"template"') && stroke.toolType != ToolType.widget) {
        canvas.save();
        canvas.translate(stroke.points.first.dx, stroke.points.first.dy);
        if (stroke.rotation != 0.0) {
          canvas.rotate(stroke.rotation);
        }

        final isUserText = stroke.toolType == ToolType.text;
        final hasBengali = stroke.text!.codeUnits.any(
          (c) => c >= 0x0980 && c <= 0x09FF,
        );
        final baseStyle = TextStyle(
          color: stroke.color,
          fontSize: stroke.size,
          height: 1.5,
        );

        // User-typed text uses a clean readable font; AI-drawn text keeps handwriting
        final textStyle = isUserText
            ? (hasBengali
                ? GoogleFonts.galada(textStyle: baseStyle)
                : GoogleFonts.inter(textStyle: baseStyle))
            : (hasBengali
                ? GoogleFonts.galada(textStyle: baseStyle)
                : GoogleFonts.nanumPenScript(textStyle: baseStyle));

        final textSpan = TextSpan(text: stroke.text, style: textStyle);
        final textPainter = TextPainter(
          text: textSpan,
          textDirection: TextDirection.ltr,
        );
        textPainter.layout(maxWidth: stroke.size * 30.0);
        textPainter.paint(canvas, Offset.zero);
        canvas.restore();

        // Draw Pins for CircuitComponents
        final comp = ComponentRegistry().createComponent(stroke);
        if (comp != null) {
          final center = stroke.bounds.center;
          for (var pin in comp.pins) {
            final pinPos = center + pin.relativePosition;
            final isOutput = pin.direction == PortDirection.output;
            final pinPaint = Paint()
              ..color = isOutput ? Colors.red.shade400 : Colors.blue.shade400
              ..style = PaintingStyle.fill;
            canvas.drawCircle(pinPos, 6.0, pinPaint);
            
            final borderPaint = Paint()
              ..color = Colors.white
              ..style = PaintingStyle.stroke
              ..strokeWidth = 1.5;
            canvas.drawCircle(pinPos, 6.0, borderPaint);
          }
          
          // Draw Oscilloscope Waveform
          if (comp.name.toLowerCase() == 'oscilloscope' && stroke.customMetadata?.containsKey('history') == true) {
            final history = (stroke.customMetadata!['history'] as List).cast<double>();
            if (history.isNotEmpty) {
              final wavePaint = Paint()
                ..color = Colors.greenAccent
                ..style = PaintingStyle.stroke
                ..strokeWidth = 2.0;
                
              final path = Path();
              final rect = stroke.bounds.inflate(20);
              // We draw the wave above the text
              final startX = rect.left;
              final width = rect.width;
              final baselineY = rect.top - 20;
              
              for (int i = 0; i < history.length; i++) {
                final x = startX + (i / 100.0) * width; // Assuming max 100 frames
                // Scale voltage: 1V = -5px (negative y is up)
                final y = baselineY - (history[i] * 5.0);
                
                if (i == 0) path.moveTo(x, y);
                else path.lineTo(x, y);
              }
              canvas.drawPath(path, wavePaint);
            }
          }
        }
        return;
      }

      if (stroke.toolType == ToolType.portal) {
        final bounds = stroke.bounds;
        final center = bounds.center;
        // Average radius from drawn bounds
        final radius = (bounds.width + bounds.height) / 4;
        
        final portalPaint = Paint()
          ..color = Colors.blue.shade300.withValues(alpha: 0.8)
          ..style = PaintingStyle.stroke
          ..strokeWidth = 4.0;
        
        final glowPaint = Paint()
          ..color = Colors.indigo.withValues(alpha: 0.3)
          ..style = PaintingStyle.fill
          ..maskFilter = const MaskFilter.blur(BlurStyle.normal, 10.0);
          
        canvas.drawCircle(center, radius, glowPaint);
        canvas.drawCircle(center, radius, portalPaint);
        return;
      }

      if (stroke.toolType == ToolType.wire) {
        final wirePaint = Paint()
          ..color = stroke.color
          ..style = PaintingStyle.stroke
          ..strokeWidth = stroke.size + 2.0
          ..strokeCap = StrokeCap.round
          ..strokeJoin = StrokeJoin.round;
          
        final corePaint = Paint()
          ..color = Colors.white.withValues(alpha: 0.5)
          ..style = PaintingStyle.stroke
          ..strokeWidth = stroke.size / 2
          ..strokeCap = StrokeCap.round
          ..strokeJoin = StrokeJoin.round;

        final path = stroke.path;
        canvas.drawPath(path, wirePaint);
        canvas.drawPath(path, corePaint);

        if (stroke.points.isNotEmpty) {
          final nodePaint = Paint()
            ..color = stroke.color
            ..style = PaintingStyle.fill;
          canvas.drawCircle(stroke.points.first, stroke.size * 2, nodePaint);
          canvas.drawCircle(stroke.points.last, stroke.size * 2, nodePaint);
        }
        return;
      }

      if (stroke.points.length == 1) {
        // Draw a single dot
        canvas.drawPoints(ui.PointMode.points, [stroke.points.first], paint);
      } else {
        // Draw cached path for massive performance gain
        final path = stroke.path;
        if (!isFill) {
          canvas.drawPath(path, paint);
        }

        if (stroke.isFilled && stroke.toolType == ToolType.pen) {
          final outlinePaint = Paint()
            ..color = Colors.black
            ..strokeWidth = 2.0
            ..style = PaintingStyle.stroke;
          canvas.drawPath(path, outlinePaint);
        }
      }
  }

  @override
  bool shouldRepaint(covariant DrawingCanvasPainter oldDelegate) {
    return true; // We can optimize this by checking if strokes changed
  }
}
