import 'package:flutter/foundation.dart';
import 'package:vinci_board/core/models/stroke.dart';
import 'package:vinci_board/engines/logic/models/circuit_component.dart';
import 'package:vinci_board/engines/logic/components/generic_component.dart';
import 'dart:convert';

typedef ComponentFactory = CircuitComponent Function(Stroke stroke);

class ComponentRegistry {
  static final ComponentRegistry _instance = ComponentRegistry._internal();
  factory ComponentRegistry() => _instance;
  ComponentRegistry._internal();

  final Map<String, ComponentFactory> _factories = {};

  void register(String keyword, ComponentFactory factory) {
    _factories[keyword.toLowerCase()] = factory;
  }

  void registerFromJson(String jsonString) {
    try {
      final Map<String, dynamic> data = jsonDecode(jsonString);
      final definition = ComponentDefinition.fromJson(data);
      GenericComponent factory(Stroke stroke) =>
          GenericComponent(stroke, definition);

      // Register all aliases
      for (var alias in definition.aliases) {
        register(alias, factory);
      }
      // Register main name
      register(definition.name, factory);
    } catch (e) {
      debugPrint('Failed to register plugin from JSON: $e');
    }
  }

  CircuitComponent? createComponent(Stroke stroke) {
    if (stroke.text == null) return null;
    String text = stroke.text!.toLowerCase();
    // Support JSON encoded widgets from ComponentDrawer
    try {
      final data = jsonDecode(stroke.text!);
      if (data != null && data['component'] != null) {
        text = (data['component'] as String).toLowerCase();
      }
    } catch (_) {}

    // Only parse as a component if the resulting text is short. This prevents entire conversational
    // paragraphs generated by the AI (which might contain words like "or", "and")
    // from being erroneously converted into logic gates.
    if (text.length > 40) return null;

    // Exact match first
    if (_factories.containsKey(text)) {
      return _factories[text]!(stroke);
    }

    // Check for exact word matches to avoid "resistor" triggering "or"
    for (var entry in _factories.entries) {
      final keyRegex = RegExp(r'\b' + RegExp.escape(entry.key) + r'\b');
      if (keyRegex.hasMatch(text)) {
        return entry.value(stroke);
      }
    }
    return null;
  }
}
